// Mocks generated by Mockito 5.4.6 from annotations
// in ttrpg_sim/test/unit/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:ttrpg_sim/core/database/database.dart' as _i2;
import 'package:ttrpg_sim/core/rules/rpg_system.dart' as _i8;
import 'package:ttrpg_sim/core/services/gemini_service.dart' as _i7;
import 'package:ttrpg_sim/core/services/gemini_wrapper.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_1 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_2 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_3 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_4 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_5 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$WorldsTable_6 extends _i1.SmartFake implements _i2.$WorldsTable {
  _Fake$WorldsTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CharacterTable_7 extends _i1.SmartFake
    implements _i2.$CharacterTable {
  _Fake$CharacterTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ChatMessagesTable_8 extends _i1.SmartFake
    implements _i2.$ChatMessagesTable {
  _Fake$ChatMessagesTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$InventoryTable_9 extends _i1.SmartFake
    implements _i2.$InventoryTable {
  _Fake$InventoryTable_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$LocationsTable_10 extends _i1.SmartFake
    implements _i2.$LocationsTable {
  _Fake$LocationsTable_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PointsOfInterestTable_11 extends _i1.SmartFake
    implements _i2.$PointsOfInterestTable {
  _Fake$PointsOfInterestTable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$NpcsTable_12 extends _i1.SmartFake implements _i2.$NpcsTable {
  _Fake$NpcsTable_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CustomTraitsTable_13 extends _i1.SmartFake
    implements _i2.$CustomTraitsTable {
  _Fake$CustomTraitsTable_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_14<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_15<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_16<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_17<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_18<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseSelectStatement_19<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_20<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_21<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_22 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerativeModelWrapper_23 extends _i1.SmartFake
    implements _i6.GenerativeModelWrapper {
  _FakeGenerativeModelWrapper_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTurnResult_24 extends _i1.SmartFake implements _i7.TurnResult {
  _FakeTurnResult_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackgroundInfo_25 extends _i1.SmartFake
    implements _i8.BackgroundInfo {
  _FakeBackgroundInfo_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GameDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameDao extends _i1.Mock implements _i2.GameDao {
  MockGameDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i2.AppDatabase);

  @override
  _i3.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_1(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i9.dummyValue<_i3.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i3.SqlTypes);

  @override
  _i3.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_2(
          this,
          Invocation.getter(#options),
        ),
      ) as _i3.DriftDatabaseOptions);

  @override
  _i3.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_3(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_4(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_5(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i3.DatabaseConnectionUser);

  @override
  _i2.$WorldsTable get worlds => (super.noSuchMethod(
        Invocation.getter(#worlds),
        returnValue: _Fake$WorldsTable_6(
          this,
          Invocation.getter(#worlds),
        ),
      ) as _i2.$WorldsTable);

  @override
  _i2.$CharacterTable get character => (super.noSuchMethod(
        Invocation.getter(#character),
        returnValue: _Fake$CharacterTable_7(
          this,
          Invocation.getter(#character),
        ),
      ) as _i2.$CharacterTable);

  @override
  _i2.$ChatMessagesTable get chatMessages => (super.noSuchMethod(
        Invocation.getter(#chatMessages),
        returnValue: _Fake$ChatMessagesTable_8(
          this,
          Invocation.getter(#chatMessages),
        ),
      ) as _i2.$ChatMessagesTable);

  @override
  _i2.$InventoryTable get inventory => (super.noSuchMethod(
        Invocation.getter(#inventory),
        returnValue: _Fake$InventoryTable_9(
          this,
          Invocation.getter(#inventory),
        ),
      ) as _i2.$InventoryTable);

  @override
  _i2.$LocationsTable get locations => (super.noSuchMethod(
        Invocation.getter(#locations),
        returnValue: _Fake$LocationsTable_10(
          this,
          Invocation.getter(#locations),
        ),
      ) as _i2.$LocationsTable);

  @override
  _i2.$PointsOfInterestTable get pointsOfInterest => (super.noSuchMethod(
        Invocation.getter(#pointsOfInterest),
        returnValue: _Fake$PointsOfInterestTable_11(
          this,
          Invocation.getter(#pointsOfInterest),
        ),
      ) as _i2.$PointsOfInterestTable);

  @override
  _i2.$NpcsTable get npcs => (super.noSuchMethod(
        Invocation.getter(#npcs),
        returnValue: _Fake$NpcsTable_12(
          this,
          Invocation.getter(#npcs),
        ),
      ) as _i2.$NpcsTable);

  @override
  _i2.$CustomTraitsTable get customTraits => (super.noSuchMethod(
        Invocation.getter(#customTraits),
        returnValue: _Fake$CustomTraitsTable_13(
          this,
          Invocation.getter(#customTraits),
        ),
      ) as _i2.$CustomTraitsTable);

  @override
  _i5.Future<int> insertMessage(
    String? role,
    String? content,
    int? worldId,
    int? characterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMessage,
          [
            role,
            content,
            worldId,
            characterId,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.ChatMessage>> getRecentMessages(
    int? characterId,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMessages,
          [
            characterId,
            limit,
          ],
        ),
        returnValue:
            _i5.Future<List<_i2.ChatMessage>>.value(<_i2.ChatMessage>[]),
      ) as _i5.Future<List<_i2.ChatMessage>>);

  @override
  _i5.Future<void> updateHp(
    int? id,
    int? newHp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHp,
          [
            id,
            newHp,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> updateCharacterStats(_i2.CharacterCompanion? stats) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterStats,
          [stats],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> updateCharacter(_i2.CharacterData? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacter,
          [entry],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> forceUpdateHp(
    int? id,
    int? newHp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #forceUpdateHp,
          [
            id,
            newHp,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateGold(
    int? id,
    int? newGold,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGold,
          [
            id,
            newGold,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateLocation(
    int? id,
    String? newLocation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [
            id,
            newLocation,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addItem(
    int? characterId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [
            characterId,
            name,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeItem(
    int? characterId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeItem,
          [
            characterId,
            name,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.CharacterData?> getCharacter(int? worldId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacter,
          [worldId],
        ),
        returnValue: _i5.Future<_i2.CharacterData?>.value(),
      ) as _i5.Future<_i2.CharacterData?>);

  @override
  _i5.Future<_i2.CharacterData?> getCharacterById(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterById,
          [characterId],
        ),
        returnValue: _i5.Future<_i2.CharacterData?>.value(),
      ) as _i5.Future<_i2.CharacterData?>);

  @override
  _i5.Future<List<_i2.CharacterData>> getCharactersForWorld(int? worldId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharactersForWorld,
          [worldId],
        ),
        returnValue:
            _i5.Future<List<_i2.CharacterData>>.value(<_i2.CharacterData>[]),
      ) as _i5.Future<List<_i2.CharacterData>>);

  @override
  _i5.Future<List<_i2.CharacterData>> getAllCharacters() => (super.noSuchMethod(
        Invocation.method(
          #getAllCharacters,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.CharacterData>>.value(<_i2.CharacterData>[]),
      ) as _i5.Future<List<_i2.CharacterData>>);

  @override
  _i5.Stream<_i2.CharacterData?> watchCharacter(int? worldId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchCharacter,
          [worldId],
        ),
        returnValue: _i5.Stream<_i2.CharacterData?>.empty(),
      ) as _i5.Stream<_i2.CharacterData?>);

  @override
  _i5.Future<List<_i2.InventoryData>> getInventory() => (super.noSuchMethod(
        Invocation.method(
          #getInventory,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.InventoryData>>.value(<_i2.InventoryData>[]),
      ) as _i5.Future<List<_i2.InventoryData>>);

  @override
  _i5.Future<List<_i2.InventoryData>> getInventoryForCharacter(
          int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInventoryForCharacter,
          [characterId],
        ),
        returnValue:
            _i5.Future<List<_i2.InventoryData>>.value(<_i2.InventoryData>[]),
      ) as _i5.Future<List<_i2.InventoryData>>);

  @override
  _i5.Stream<List<_i2.InventoryData>> watchInventory() => (super.noSuchMethod(
        Invocation.method(
          #watchInventory,
          [],
        ),
        returnValue: _i5.Stream<List<_i2.InventoryData>>.empty(),
      ) as _i5.Stream<List<_i2.InventoryData>>);

  @override
  _i5.Future<int> debugCountCharacters() => (super.noSuchMethod(
        Invocation.method(
          #debugCountCharacters,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> createWorld(_i2.WorldsCompanion? world) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorld,
          [world],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.World>> getAllWorlds() => (super.noSuchMethod(
        Invocation.method(
          #getAllWorlds,
          [],
        ),
        returnValue: _i5.Future<List<_i2.World>>.value(<_i2.World>[]),
      ) as _i5.Future<List<_i2.World>>);

  @override
  _i5.Future<_i2.World?> getWorld(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getWorld,
          [id],
        ),
        returnValue: _i5.Future<_i2.World?>.value(),
      ) as _i5.Future<_i2.World?>);

  @override
  _i5.Future<void> deleteWorld(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorld,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateCharacterBio({
    required int? characterId,
    required String? name,
    required String? species,
    required String? origin,
    required String? attributes,
    required String? skills,
    required String? traits,
    required String? feats,
    required String? background,
    String? backstory,
    List<String>? inventory,
    required int? level,
    required int? maxHp,
    int? strength = 10,
    int? dexterity = 10,
    int? constitution = 10,
    int? intelligence = 10,
    int? wisdom = 10,
    int? charisma = 10,
    String? spells = '[]',
    int? currentMana = 10,
    int? maxMana = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterBio,
          [],
          {
            #characterId: characterId,
            #name: name,
            #species: species,
            #origin: origin,
            #attributes: attributes,
            #skills: skills,
            #traits: traits,
            #feats: feats,
            #background: background,
            #backstory: backstory,
            #inventory: inventory,
            #level: level,
            #maxHp: maxHp,
            #strength: strength,
            #dexterity: dexterity,
            #constitution: constitution,
            #intelligence: intelligence,
            #wisdom: wisdom,
            #charisma: charisma,
            #spells: spells,
            #currentMana: currentMana,
            #maxMana: maxMana,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Location?> getLocation(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [id],
        ),
        returnValue: _i5.Future<_i2.Location?>.value(),
      ) as _i5.Future<_i2.Location?>);

  @override
  _i5.Future<List<_i2.Location>> getLocationsForWorld(int? worldId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationsForWorld,
          [worldId],
        ),
        returnValue: _i5.Future<List<_i2.Location>>.value(<_i2.Location>[]),
      ) as _i5.Future<List<_i2.Location>>);

  @override
  _i5.Future<List<_i2.PointsOfInterestData>> getPoisForLocation(
          int? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPoisForLocation,
          [locationId],
        ),
        returnValue: _i5.Future<List<_i2.PointsOfInterestData>>.value(
            <_i2.PointsOfInterestData>[]),
      ) as _i5.Future<List<_i2.PointsOfInterestData>>);

  @override
  _i5.Future<List<_i2.Npc>> getNpcsForLocation(int? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNpcsForLocation,
          [locationId],
        ),
        returnValue: _i5.Future<List<_i2.Npc>>.value(<_i2.Npc>[]),
      ) as _i5.Future<List<_i2.Npc>>);

  @override
  _i5.Future<List<_i2.Npc>> getNpcsForWorld(int? worldId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNpcsForWorld,
          [worldId],
        ),
        returnValue: _i5.Future<List<_i2.Npc>>.value(<_i2.Npc>[]),
      ) as _i5.Future<List<_i2.Npc>>);

  @override
  _i5.Future<List<_i2.Npc>> getNpcsForPoi(int? poiId) => (super.noSuchMethod(
        Invocation.method(
          #getNpcsForPoi,
          [poiId],
        ),
        returnValue: _i5.Future<List<_i2.Npc>>.value(<_i2.Npc>[]),
      ) as _i5.Future<List<_i2.Npc>>);

  @override
  _i5.Future<int> createLocation(_i2.LocationsCompanion? loc) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocation,
          [loc],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> createLocationFromValues({
    required int? worldId,
    required String? name,
    required String? description,
    required String? type,
    String? coordinates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationFromValues,
          [],
          {
            #worldId: worldId,
            #name: name,
            #description: description,
            #type: type,
            #coordinates: coordinates,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> createPoi(_i2.PointsOfInterestCompanion? poi) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPoi,
          [poi],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> createPoiFromValues({
    required int? locationId,
    required String? name,
    required String? description,
    required String? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPoiFromValues,
          [],
          {
            #locationId: locationId,
            #name: name,
            #description: description,
            #type: type,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> createNpc(_i2.NpcsCompanion? npc) => (super.noSuchMethod(
        Invocation.method(
          #createNpc,
          [npc],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> createNpcFromValues({
    required int? worldId,
    required int? locationId,
    required String? name,
    required String? role,
    required String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNpcFromValues,
          [],
          {
            #worldId: worldId,
            #locationId: locationId,
            #name: name,
            #role: role,
            #description: description,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> deleteCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCharacter,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateCharacterLocation(
    int? charId,
    int? locationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterLocation,
          [
            charId,
            locationId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> createCustomTrait(_i2.CustomTraitsCompanion? trait) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomTrait,
          [trait],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.CustomTrait>> getCustomTraitsByType(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomTraitsByType,
          [type],
        ),
        returnValue:
            _i5.Future<List<_i2.CustomTrait>>.value(<_i2.CustomTrait>[]),
      ) as _i5.Future<List<_i2.CustomTrait>>);

  @override
  _i5.Stream<List<_i2.CustomTrait>> watchCustomTraitsByType(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchCustomTraitsByType,
          [type],
        ),
        returnValue: _i5.Stream<List<_i2.CustomTrait>>.empty(),
      ) as _i5.Stream<List<_i2.CustomTrait>>);

  @override
  _i5.Future<void> deleteCustomTrait(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCustomTrait,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
          _i4.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i5.Stream<T>.empty(),
      ) as _i5.Stream<T>);

  @override
  T alias<T, D>(
    _i3.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i9.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<Set<_i3.TableUpdate>> tableUpdates(
          [_i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i5.Stream<Set<_i3.TableUpdate>>.empty(),
      ) as _i5.Stream<Set<_i3.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
          _i5.FutureOr<T> Function(_i3.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_14<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_15<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
          _i3.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_16<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_17<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_18<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
          Iterable<_i3.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeBaseSelectStatement_19<_i3.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_20<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i3.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
      ) as _i5.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_21<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_21<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i5.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_14<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_14<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_14<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_22(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_22(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GeminiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiService extends _i1.Mock implements _i7.GeminiService {
  MockGeminiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GenerativeModelWrapper createModel(String? instruction) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModel,
          [instruction],
        ),
        returnValue: _FakeGenerativeModelWrapper_23(
          this,
          Invocation.method(
            #createModel,
            [instruction],
          ),
        ),
      ) as _i6.GenerativeModelWrapper);

  @override
  _i5.Future<_i7.TurnResult> sendMessage(
    String? userMessage,
    _i2.GameDao? dao,
    int? worldId, {
    required String? genre,
    required String? tone,
    required String? description,
    required _i2.CharacterData? player,
    required List<String>? features,
    required Map<String, int>? spellSlots,
    required List<String>? spells,
    _i2.Location? location,
    List<_i2.PointsOfInterestData>? pois = const [],
    List<_i2.Npc>? npcs = const [],
    String? worldKnowledge,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            userMessage,
            dao,
            worldId,
          ],
          {
            #genre: genre,
            #tone: tone,
            #description: description,
            #player: player,
            #features: features,
            #spellSlots: spellSlots,
            #spells: spells,
            #location: location,
            #pois: pois,
            #npcs: npcs,
            #worldKnowledge: worldKnowledge,
          },
        ),
        returnValue: _i5.Future<_i7.TurnResult>.value(_FakeTurnResult_24(
          this,
          Invocation.method(
            #sendMessage,
            [
              userMessage,
              dao,
              worldId,
            ],
            {
              #genre: genre,
              #tone: tone,
              #description: description,
              #player: player,
              #features: features,
              #spellSlots: spellSlots,
              #spells: spells,
              #location: location,
              #pois: pois,
              #npcs: npcs,
              #worldKnowledge: worldKnowledge,
            },
          ),
        )),
      ) as _i5.Future<_i7.TurnResult>);

  @override
  _i5.Future<_i7.TurnResult> sendFunctionResponse(
    String? functionName,
    Map<String, dynamic>? response,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFunctionResponse,
          [
            functionName,
            response,
          ],
        ),
        returnValue: _i5.Future<_i7.TurnResult>.value(_FakeTurnResult_24(
          this,
          Invocation.method(
            #sendFunctionResponse,
            [
              functionName,
              response,
            ],
          ),
        )),
      ) as _i5.Future<_i7.TurnResult>);
}

/// A class which mocks [RpgSystem].
///
/// See the documentation for Mockito's code generation for more information.
class MockRpgSystem extends _i1.Mock implements _i8.RpgSystem {
  MockRpgSystem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get availableClasses => (super.noSuchMethod(
        Invocation.getter(#availableClasses),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get availableSpecies => (super.noSuchMethod(
        Invocation.getter(#availableSpecies),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get availableBackgrounds => (super.noSuchMethod(
        Invocation.getter(#availableBackgrounds),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get availableFeats => (super.noSuchMethod(
        Invocation.getter(#availableFeats),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void registerCustomTraits(List<_i2.CustomTrait>? traits) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomTraits,
          [traits],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.BackgroundInfo getBackgroundInfo(String? backgroundName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundInfo,
          [backgroundName],
        ),
        returnValue: _FakeBackgroundInfo_25(
          this,
          Invocation.method(
            #getBackgroundInfo,
            [backgroundName],
          ),
        ),
      ) as _i8.BackgroundInfo);

  @override
  int calculateMaxHp(
    String? characterClass,
    int? level,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMaxHp,
          [
            characterClass,
            level,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  Map<String, int> getMaxSpellSlots(
    String? charClass,
    int? level,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMaxSpellSlots,
          [
            charClass,
            level,
          ],
        ),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  List<String> getClassFeatures(
    String? charClass,
    int? level,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassFeatures,
          [
            charClass,
            level,
          ],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> getKnownSpells(
    String? charClass,
    int? level,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKnownSpells,
          [
            charClass,
            level,
          ],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  int getModifier(
    _i2.CharacterData? character,
    String? checkName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModifier,
          [
            character,
            checkName,
          ],
        ),
        returnValue: 0,
      ) as int);
}
